#!/usr/bin/env python3
# DO NOT HAND-EDIT consumers of this script's output.
# Generated by: scripts/build_parliament_libraries.py
#
# Joins sansad-semantic-crawler outputs (manifest + analysis_discourse +
# ministry_summary_qa) into assets/parliament_libraries.js, the dataset
# the public data page consumes.
#
# Runs after `make corpus-refresh` and `make corpus-analyse`. The upstream
# package's `export` subcommand emits the same manifest-derived summary
# but does not merge the v1.0.0 discourse-analysis files, so this adapter
# fills that gap.

from __future__ import annotations

import datetime as dt
import json
from collections import Counter, defaultdict
from html import escape
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CORPUS = REPO / "data" / "_parliament_libraries"
EXPORT = REPO / "assets" / "parliament_libraries.js"

MANIFEST = CORPUS / "manifest.jsonl"
DISCOURSE = CORPUS / "analysis_discourse.jsonl"
ANSWERS = CORPUS / "answers.jsonl"
MINISTRY = CORPUS / "ministry_summary_qa.jsonl"

# Labels the classifier emits, grouped by political function.
EVASIVE_LABELS = {
    "DEFLECTED",
    "ABSORBED",
    "REJECTED",
    "SUBSTITUTED",
    "DATA_WITHHELD",
    "SCOPE_NARROWED",
    "CIRCULAR_REFERENCE",
    "FEDERAL_DEFLECTION",
    "STRUCTURAL_REFUSAL",
    "CONSTITUTIONAL_DEFAULT",
    "REPRESENTATIONAL_SILENCE",
}
SUBSTANTIVE_LABELS = {"ACCEPTED", "FACTUAL_DISCLOSURE"}

# Representative excerpts to surface on the site: pick at most this many
# per evasion label, keep the highest-confidence ones.
EXCERPTS_PER_LABEL = 2
EXCERPT_MAX_CHARS = 320


def load_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


def existing_export() -> dict:
    """Read the manifest-derived base export the package produces."""
    text = EXPORT.read_text()
    start = text.index("{")
    return json.loads(text[start:].rstrip().rstrip(";"))


def shorten(s: str, n: int = EXCERPT_MAX_CHARS) -> str:
    s = " ".join(s.split())
    return s if len(s) <= n else s[: n - 1].rstrip() + "…"


def build_discourse_summary(discourse: list[dict], questions_total: int) -> dict:
    labels = Counter(r.get("label", "UNCLASSIFIED") for r in discourse)
    classified = sum(c for lab, c in labels.items() if lab != "UNCLASSIFIED")
    evasive = sum(c for lab, c in labels.items() if lab in EVASIVE_LABELS)
    substantive = sum(c for lab, c in labels.items() if lab in SUBSTANTIVE_LABELS)
    rate = round(evasive / classified, 4) if classified else None
    return {
        "questionsTotal": questions_total,
        "responsesExtracted": len(discourse),
        "responsesClassified": classified,
        "evasiveCount": evasive,
        "substantiveCount": substantive,
        "evasionRateClassified": rate,
        "labelDistribution": dict(labels.most_common()),
    }


def build_ministry_discourse(ministry_rows: list[dict]) -> list[dict]:
    out = []
    for row in sorted(ministry_rows, key=lambda r: -r.get("records_total", 0)):
        out.append(
            {
                "ministry": row["ministry"],
                "recordsTotal": row["records_total"],
                "recordsClassified": row.get("records_classified", 0),
                "recordsUnclassified": row.get("records_unclassified", 0),
                "evasionRateClassified": row.get("evasion_rate_classified"),
                "labelDistribution": row.get("label_distribution", {}),
                "perEvasionShare": row.get("per_evasion_label_share", {}),
            }
        )
    return out


def build_excerpts(
    discourse: list[dict],
    by_key: dict[str, dict],
) -> list[dict]:
    by_label: dict[str, list[dict]] = defaultdict(list)
    for rec in discourse:
        label = rec.get("label")
        if label not in EVASIVE_LABELS:
            continue
        manifest = by_key.get(rec["key"])
        if not manifest:
            continue
        by_label[label].append({"rec": rec, "manifest": manifest})

    out: list[dict] = []
    for label in sorted(by_label):
        picks = sorted(
            by_label[label],
            key=lambda x: -float(x["rec"].get("confidence", 0)),
        )[:EXCERPTS_PER_LABEL]
        for p in picks:
            rec, m = p["rec"], p["manifest"]
            out.append(
                {
                    "label": label,
                    "ministry": m.get("ministry", ""),
                    "house": m.get("house", ""),
                    "qtype": m.get("qtype", ""),
                    "qno": m.get("qno", ""),
                    "date": m.get("date", ""),
                    "title": escape(m.get("title", "")),
                    "askers": m.get("askers", []),
                    "tags": m.get("tags", []),
                    "excerpt": shorten(rec.get("text_excerpt", "")),
                    "matchedPattern": rec.get("matched_pattern", ""),
                    "politicalFunction": rec.get("political_function", ""),
                    "confidence": rec.get("confidence"),
                    "uri": m.get("uri", ""),
                }
            )
    return out


def build_rrrlf_deflections(
    discourse: list[dict],
    by_key: dict[str, dict],
) -> list[dict]:
    """The 'Library is a State subject' cascade: FEDERAL_DEFLECTION on RRRLF-tagged questions.

    This is the structural keystone of the page's pair argument: the
    Centre's library-funding arm exists, and the Centre justifies its
    smallness by deflecting library policy to the States — in the same
    five words, across decades and dispensations.
    """
    out: list[dict] = []
    for rec in discourse:
        if rec.get("label") != "FEDERAL_DEFLECTION":
            continue
        m = by_key.get(rec["key"])
        if not m or "rrrlf" not in (m.get("tags") or []):
            continue
        out.append(
            {
                "ministry": m.get("ministry", ""),
                "house": m.get("house", ""),
                "qtype": m.get("qtype", ""),
                "qno": m.get("qno", ""),
                "date": m.get("date", ""),
                "title": escape(m.get("title", "")),
                "askers": m.get("askers", []),
                "matchedPattern": rec.get("matched_pattern", ""),
                "excerpt": shorten(rec.get("text_excerpt", "")),
                "politicalFunction": rec.get("political_function", ""),
                "uri": m.get("uri", ""),
            }
        )
    out.sort(key=lambda x: x.get("date", ""))
    return out


def main() -> None:
    manifest = load_jsonl(MANIFEST)
    discourse = load_jsonl(DISCOURSE)
    ministry_rows = load_jsonl(MINISTRY)

    by_key = {m["key"]: m for m in manifest}

    base = existing_export()
    base["generatedAt"] = dt.datetime.now().replace(microsecond=0).isoformat()
    base["discourseSummary"] = build_discourse_summary(discourse, len(manifest))
    base["ministryDiscourse"] = build_ministry_discourse(ministry_rows)
    base["discourseExcerpts"] = build_excerpts(discourse, by_key)
    base["rrrlfDeflections"] = build_rrrlf_deflections(discourse, by_key)

    payload = json.dumps(base, indent=2, ensure_ascii=False)
    EXPORT.write_text(f"window.PARLIAMENT_LIBRARY_DATA = {payload};\n")

    summary = base["discourseSummary"]
    print(f"wrote {EXPORT.relative_to(REPO)}")
    print(
        f"  responses extracted: {summary['responsesExtracted']}"
        f" · classified: {summary['responsesClassified']}"
        f" · evasion rate: {summary['evasionRateClassified']}"
    )
    print(f"  ministries: {len(base['ministryDiscourse'])}")
    print(f"  excerpts: {len(base['discourseExcerpts'])}")
    print(f"  rrrlf deflections: {len(base['rrrlfDeflections'])}")


if __name__ == "__main__":
    main()
